### ISSUE TITLE
where is the file "SSY_ARC_OR_NO_ARC.h"?

### ISSUE THREAD

**Issue by yuedong56** [jerrykrinock/CategoriesObjC#4]
I cant find it

**Comment by jerrykrinock** [comment]
Hello, @yuedong56.

It's a file that contains a weird compound macro to support ARC-or-notd in *really* old projects that use like the 10.6 SDK, before __has_feature was available.  For the gory details, [here it is](https://github.com/jerrykrinock/Headers/blob/master/SSY_ARC_OR_NO_ARC.h).

Since none of my libraries go back to support 10.6 any more, you should just eliminate that #include and patch any errors which occur by using `#if __has_feature(objc_arc)`
